-- =====================================================
-- SMYTTEN E-COMMERCE DATABASE
-- SELLER AND INVENTORY MANAGEMENT
-- =====================================================

-- 1. CREATE SELLER TABLE

CREATE TABLE SELLER (
    SELLER_ID NUMBER PRIMARY KEY,
    SELLER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE_NUMBER VARCHAR2(15) UNIQUE,
    ADDRESS VARCHAR2(255)
);


-- 2. INSERT SELLER RECORDS

INSERT INTO SELLER
VALUES (501, 'Lakshmi Beauty Store', 'lakshmi@gmail.com',
        '9000000001', 'Chennai');

INSERT INTO SELLER
VALUES (502, 'Glow Cosmetics', 'glow@gmail.com',
        '9000000002', 'Coimbatore');

INSERT INTO SELLER
VALUES (503, 'Nature Care', 'naturecare@gmail.com',
        '9000000003', 'Madurai');

INSERT INTO SELLER
VALUES (504, 'Urban Beauty', 'urbanbeauty@gmail.com',
        '9000000004', 'Salem');

INSERT INTO SELLER
VALUES (505, 'Pure Essentials', 'pureessentials@gmail.com',
        '9000000005', 'Trichy');

COMMIT;


-- 3. CREATE INVENTORY TABLE

CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER PRIMARY KEY,
    SELLER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    AVAILABLE_STOCK NUMBER NOT NULL
        CHECK (AVAILABLE_STOCK >= 0),
    LAST_UPDATED DATE DEFAULT SYSDATE,
    PRODUCT_STATUS VARCHAR2(20) NOT NULL
);


-- 4. ESTABLISH RELATIONSHIP WITH SELLER

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_SELLER
FOREIGN KEY (SELLER_ID)
REFERENCES SELLER(SELLER_ID);


-- 5. ESTABLISH RELATIONSHIP WITH PRODUCT

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT2(PRODUCT_ID);


-- 6. INSERT INVENTORY RECORDS

INSERT INTO INVENTORY
VALUES (601, 501, 101, 50, SYSDATE, 'Available');

INSERT INTO INVENTORY
VALUES (602, 502, 102, 0, SYSDATE, 'Unavailable');

INSERT INTO INVENTORY
VALUES (603, 503, 103, 25, SYSDATE, 'Available');

INSERT INTO INVENTORY
VALUES (604, 504, 104, 10, SYSDATE, 'Available');

INSERT INTO INVENTORY
VALUES (605, 505, 105, 0, SYSDATE, 'Unavailable');

COMMIT;


-- 7. DISPLAY SELLER DETAILS

SELECT *
FROM SELLER;


-- 8. DISPLAY INVENTORY DETAILS

SELECT *
FROM INVENTORY;


-- 9. SELLER PRODUCT INFORMATION

SELECT
    S.SELLER_ID,
    S.SELLER_NAME,
    I.PRODUCT_ID,
    I.AVAILABLE_STOCK,
    I.PRODUCT_STATUS
FROM SELLER S
JOIN INVENTORY I
ON S.SELLER_ID = I.SELLER_ID;


-- 10. INVENTORY STATUS REPORT

SELECT
    I.INVENTORY_ID,
    S.SELLER_NAME,
    I.PRODUCT_ID,
    I.AVAILABLE_STOCK,
    I.PRODUCT_STATUS,
    I.LAST_UPDATED
FROM INVENTORY I
JOIN SELLER S
ON I.SELLER_ID = S.SELLER_ID
ORDER BY I.PRODUCT_STATUS, I.PRODUCT_ID;


-- 11. AVAILABLE PRODUCTS

SELECT *
FROM INVENTORY
WHERE PRODUCT_STATUS = 'Available';


-- 12. UNAVAILABLE PRODUCTS

SELECT *
FROM INVENTORY
WHERE PRODUCT_STATUS = 'Unavailable';